### ISSUE TITLE
Add redirects to queue

### ISSUE THREAD

**Issue by Mynyx** [terminal42/escargot#12]
The crawler immediately follows redirects instead of adding the target to the queue.

One disadvantage of this is that the target page is processed again, even if it has already been crawled.

**Comment by Toflar** [comment]
Can you check if https://github.com/terminal42/escargot/pull/13 fixes your issue?

**Comment by Toflar** [comment]
Closing in favour of the pull request, you may comment there if everything is fine or not :)
