### ISSUE TITLE
Allow Symfony 5 dependencies

### ISSUE THREAD

**Issue by aleksblendwerk** [terminal42/escargot#14]
Could you update `composer.json` to allow the 5.x versions of the `symfony` dependencies?

Wanted to take Escargot for a test drive within a project that uses those...

Looks like a very promising library!

**Comment by Toflar** [comment]
Just released 0.5.9! Let me know how things go for your project and what you're doing with it :) I've opened a new section in the README that lists projects that use Escargot :)
