### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by math-GH** [terminal42/escargot#16]
Contao 4.9.2

![grafik](https://user-images.githubusercontent.com/1645099/81862008-5b0e7400-9569-11ea-9803-50516642029c.png)

File
    Source,URI,"Found on URI","Found on level",Tags,Message
    "Terminal42\Escargot\Escargot",https://domain.tld/,,0,,"Exception of type ""Symfony\Component\HttpClient\Exception\TransportException"" occurred: SSL peer certificate or SSH remote key was not OK for ""https://domain.tld/""."
    "Contao\CoreBundle\Crawl\Escargot\Subscriber\SearchIndexSubscriber",https://domain.tld/,,0,,"Broken link! Could not request properly: SSL peer certificate or SSH remote key was not OK for ""https://domain.tld/"".."
    "Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 1 request(s)."

Reason: SSL certificate is not signed for that (sub)domain (because it is a subdomain for testing/creating new release)

Maybe an error could occur on the site.

**Comment by Toflar** [comment]
That's not an Escargot issue. An also there is an error...
