### ISSUE TITLE
Change the log level for successful actions

### ISSUE THREAD

**Issue by leofeyer** [terminal42/escargot#2]
I want to log all successful requests in order to see what the crawler does. However, the output was cluttered with UriFilter excludes, which made it hard to extract the useful information.

Maybe you can change the log level from `debug` to `notice` in the `onSuccessfulResponse()` and `onFinishedCrawling()` methods of the `LoggerSubscriber` class? Then `-vv` will print all successful actions and only `-vvv` will print everything.

**Comment by Toflar** [comment]
Good idea, changed in ca1ba8f.
