### ISSUE TITLE
Crawler does not handle redirecs for robots.txt requests

### ISSUE THREAD

**Issue by leofeyer** [terminal42/escargot#20]
URL: https://de.contaowiki.org/robots.txt
Response: 301 → https://de.contaowiki.org/Robots.txt
The target page does not exist (404)

<img width="1182" alt="" src="https://user-images.githubusercontent.com/1192057/112619509-b6ff8580-8e27-11eb-871e-fe1bd98d47e0.png">

The problem is that the robots subscriber only handles exceptions that implement the `TransportExceptionInterface`.

https://github.com/terminal42/escargot/blob/faad8af1d62835cbe7f33530eb42b7609849f143/src/Subscriber/RobotsSubscriber.php#L190-L192

In this case, however, the exception is a `Symfony\Component\HttpClient\Exception\RedirectionException`.

**Comment by Toflar** [comment]
The `RedirectException` should only be thrown lazily, once `$response->getContent()` is executed. The only exception that is allowed to be thrown there is the `TransportExceptionInterface` exception. 
Also see https://symfony.com/doc/current/http_client.html#handling-exceptions.

And I'm properly handling the status code before accessing the content:

https://github.com/terminal42/escargot/blob/faad8af1d62835cbe7f33530eb42b7609849f143/src/Subscriber/RobotsSubscriber.php#L180-L184

I've also tried to reproduce your issue using `https://de.contaowiki.org/robots.txt` but I'm unable to do so.
For some reason, the `symfony/http-client` throws an exception for you although it should not. Might be that there's an issue in your `symfony/http-client` version (make sure you use the latest one) or you may have encountered a weird cURL issue/incompatibility which `symfony/http-client` doesn't handle properly (yet).

You might debug what `$response->getInfo()` contains in it's `debug` key. You should see all HTTP requests including their redirects etc. there.
