### ISSUE TITLE
Incompatibility with Doctrine DBAL 3 (Contao 4.13)

### ISSUE THREAD

**Issue by aschempp** [terminal42/escargot#22]
Unfortunately, the package is currently incompatible with DBAL 3 since they removed the Synchronizer package (https://github.com/doctrine/dbal/blob/3.2.x/UPGRADE.md#bc-break-removed-synchronizer-package) which is used in the `DoctrineQueue` (https://github.com/terminal42/escargot/blob/main/src/Queue/DoctrineQueue.php#L17).

This unfortunately breaks Contao 4.13 (4.x-dev), the search index cannot be rebuilt in the back end.

**Comment by Toflar** [comment]
I'm sorry it's breaking another package but this one is going to take a rather long time to fix...

**Comment by Toflar** [comment]
Holy...here we go, can you test if https://github.com/terminal42/escargot/pull/23 fixes the problem?
