### ISSUE TITLE
Can not Start Crawler on Contao 4.9.21 - Attempted to call an undefined method named "withHttpClient" 

### ISSUE THREAD

**Issue by marcelmuellerio** [terminal42/escargot#24]
Hello,

We have the Problem that we can not Generate the Contao SearchIndex (Crawler)
Error: Attempted to call an undefined method named "withHttpClient" of class "Terminal42\Escargot\Escargot".

Do you have any Infos for us ?

**Comment by Toflar** [comment]
Looks like you have incompatible versions installed. Try running a full `composer update` so all dependencies are updated.
