### ISSUE TITLE
Crawling protected pages seems broken

### ISSUE THREAD

**Issue by bennyborn** [terminal42/escargot#29]
Our customer has some pages which are protected by a member login. 
Of course within the `config.yml` he has set `index_protected` to `true`.
He started the crawl by selecting a member with sufficient permissions, frontend preview with this member also works flawlessly, but in the debug.log it is stated that the crawler receives a HTTP 401 for each protected page.

It seems like the crawler is not using the selected member to perform the requests at all.

I could also recreate the same problem on a fresh 4.13 installation.

Link to the discussion in Slack for reference: https://contao.slack.com/archives/CK4J0KNDB/p1669813587617539

**Comment by fritzmg** [comment]
I don't think this has anything to do with `terminal42/escargot` directly, as this is a feature of Contao back end.

If this is reproducible in a clean Contao 4.13 instance, you should open a ticket at https://github.com/contao/contao/issues
