### ISSUE TITLE
Crawl URI in the request exception event

### ISSUE THREAD

**Issue by leofeyer** [terminal42/escargot#4]
Wouldn't it be helpful if the `RequestExceptionEvent` class inherited from the `AbstractResponseEvent` as well? This way we would have access to the crawl URI in the exception listener.

**Comment by Toflar** [comment]
The `RequestExceptionEvent` provides access to the `Response` but when an exception happens before the request is even sent, you don't get any response which is why that's optional. The `AbstractResponseEvent` enforces a response :)

**Comment by leofeyer** [comment]
It does not work anyway. As briefly discussed on Slack, we need an `UnsuccessfulResponseEvent` in case the response status is not 200.

**Comment by Toflar** [comment]
That's already implemented on master?

**Comment by leofeyer** [comment]
You are fast. 👍
