### ISSUE TITLE
Remove support for robots.txt

### ISSUE THREAD

**Issue by Toflar** [terminal42/escargot#5]
Google announced that they will stop supporting the `robots.txt`. There's enough support with `<meta>` tags and/or HTTP headers.

Let's drop it, it will also reduce dependencies :) 

Source: https://webmasters.googleblog.com/2019/07/a-note-on-unsupported-rules-in-robotstxt.html

**Comment by leofeyer** [comment]
They will not be dropping support for `robots.txt` files in general:

> In the interest of maintaining a healthy ecosystem and preparing for potential future open source releases, we're retiring all **code that handles unsupported and unpublished rules** (such as noindex) on September 1, 2019.

But since `noindex` is probably the interesting bit for a crawler, it should be safe for Escargot to ignore the `robots.txt` file. (Unless there is `Disallow: Escargot` in it maybe.)

**Comment by Toflar** [comment]
Yeah my POV is that `Disallow: Escargot` can be safely ignored. You are using the indexer, so why would you ignore yourself? 😄

**Comment by leofeyer** [comment]
Well, I could use the crawler to index your site as well. 😀

**Comment by Toflar** [comment]
Yeah, I don't care about this case at all tbh.

**Comment by Toflar** [comment]
I will have to look into this again and rework the implementation. I seem to have misunderstood what Google does. They're not deprecating the `Disallow` and `Allow` directives.

**Comment by Toflar** [comment]
I'm about to re-introduced it in https://github.com/terminal42/escargot/pull/7.
